runtime: python311
service: collision-detector  # Replace with your desired service name

instance_class: F2  # Specifies the instance class (F2 is for small services)

env_variables:  # Define environment variables
  FLASK_ENV: production
  PORT: 8080

handlers:
  - url: /.*
    script: auto  # Automatic detection of the app entry point
